version: "3.7"

services:
  database:
    image: postgres
    container_name: database_series_movies
    restart: always
    ports:
      - 5432:5432
    env_file:
      - docker.env
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: series_movies
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
